name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install project dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android

      - name: Set Gradle 7.6.1
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6.1-bin.zip
          unzip -q gradle-7.6.1-bin.zip
          echo "${PWD}/gradle-7.6.1/bin" >> $GITHUB_PATH

      - name: Build APK
        run: cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: platforms/android/app/build/outputs/apk/release/app-release.apk
